// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class Conversation {
    "ID": number;
    "Title": string;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Conversation instance. */
    constructor($$source: Partial<Conversation> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     */
    static createFrom($$source: any = {}): Conversation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conversation($$parsedSource as Partial<Conversation>);
    }
}

export class Message {
    "ID": number;
    "ConversationID": number;
    "Role": string;
    "Content": string;
    "Attachments": string;
    "ToolCalls": string;
    "CreatedAt": time$0.Time;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("ConversationID" in $$source)) {
            this["ConversationID"] = 0;
        }
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("Attachments" in $$source)) {
            this["Attachments"] = "";
        }
        if (!("ToolCalls" in $$source)) {
            this["ToolCalls"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * Persona is a named instruction block prepended to outgoing user prompts when selected.
 */
export class Persona {
    "ID": number;
    "Name": string;
    "Prompt": string;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Persona instance. */
    constructor($$source: Partial<Persona> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Prompt" in $$source)) {
            this["Prompt"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Persona instance from a string or object.
     */
    static createFrom($$source: any = {}): Persona {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Persona($$parsedSource as Partial<Persona>);
    }
}
