package tools

var DefaultIgnoredDirs = map[string]bool{
	".git":          true,
	"node_modules":  true,
	"vendor":        true,
	"__pycache__":   true,
	".next":         true,
	"dist":          true,
	"build":         true,
	".cache":        true,
	".svn":          true,
	"target":        true,
	".gradle":       true,
	"bin":           true,
	"obj":           true,
	".venv":         true,
	"venv":          true,
	"env":           true,
	".bundle":       true,
	"out":           true,
	".nuxt":         true,
	".svelte-kit":   true,
	"*.xcodeproj":   true,
	".idea":         true,
	".vscode":       true,
	"packages":      true,
	"Pods":          true,
	"Carthage":      true,
	"_build":        true,
	".m2":           true,
	".sbt":          true,
	".cabal":        true,
	"dist-newstyle": true,
	".dart_tool":    true,
	"vendor/bundle": true,
}
