// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AbortMessage(): $CancellablePromise<void> {
    return $Call.ByID(3355598392);
}

export function CreateConversation(): $CancellablePromise<$models.Conversation | null> {
    return $Call.ByID(1021935206).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreatePersona adds a persona. Name must be non-empty after trim.
 */
export function CreatePersona(name: string, prompt: string): $CancellablePromise<$models.Persona | null> {
    return $Call.ByID(1037668371, name, prompt).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DeleteAllConversations(): $CancellablePromise<void> {
    return $Call.ByID(4177670995);
}

export function DeleteConversation(id: number): $CancellablePromise<void> {
    return $Call.ByID(1702807921, id);
}

export function DeleteMessage(conversationID: number, messageIndex: number): $CancellablePromise<void> {
    return $Call.ByID(4055978473, conversationID, messageIndex);
}

/**
 * DeletePersona removes a persona and clears active selection if it pointed at this id.
 */
export function DeletePersona(id: number): $CancellablePromise<void> {
    return $Call.ByID(1746360650, id);
}

/**
 * GetActivePersonaID returns the persisted selection, or "" for none.
 */
export function GetActivePersonaID(): $CancellablePromise<string> {
    return $Call.ByID(1075047218);
}

export function GetAvailableProviders(): $CancellablePromise<{ [_ in string]?: string }[]> {
    return $Call.ByID(1292387576).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetConversations(): $CancellablePromise<$models.Conversation[]> {
    return $Call.ByID(1884408553).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetDefaultSystemPrompt returns the built-in default system prompt so the frontend can offer "Reset to Default".
 */
export function GetDefaultSystemPrompt(): $CancellablePromise<string> {
    return $Call.ByID(2083466055);
}

export function GetMessages(conversationID: number): $CancellablePromise<$models.Message[]> {
    return $Call.ByID(3832618599, conversationID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetPersonas returns all personas (empty if DB unavailable).
 */
export function GetPersonas(): $CancellablePromise<$models.Persona[]> {
    return $Call.ByID(130544366).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetSettings(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType4($result);
    });
}

export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(3283000736);
}

/**
 * OpenPath opens a file or folder with the OS default handler. Returns "" on success, else an error message.
 */
export function OpenPath(path: string): $CancellablePromise<string> {
    return $Call.ByID(1591734570, path);
}

export function RegenerateMessage(conversationID: number, messageIndex: number, selectedPersonaID: string): $CancellablePromise<string> {
    return $Call.ByID(1824713638, conversationID, messageIndex, selectedPersonaID);
}

export function SaveSettings(settings: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(1949631069, settings);
}

export function SearchMessages(query: string): $CancellablePromise<{ [_ in `${number}`]?: $models.Message[] }> {
    return $Call.ByID(3203246577, query).then(($result: any) => {
        return $$createType10($result);
    });
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(2427571203);
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(237181597);
}

export function SendMessage(conversationID: number, content: string, selectedPersonaID: string, attachmentsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(1496882310, conversationID, content, selectedPersonaID, attachmentsJSON);
}

export function SendMessageWithImages(conversationID: number, content: string, imageDataURLs: string[], selectedPersonaID: string, attachmentsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(4272898556, conversationID, content, imageDataURLs, selectedPersonaID, attachmentsJSON);
}

/**
 * SetActivePersonaID sets the global active persona; empty string means none (no prefix when 2+ personas).
 */
export function SetActivePersonaID(id: string): $CancellablePromise<void> {
    return $Call.ByID(3383041646, id);
}

export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4214292049, key, value);
}

export function SignIn(): $CancellablePromise<string> {
    return $Call.ByID(749131203);
}

export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(578162832);
}

export function TestConnection(): $CancellablePromise<string> {
    return $Call.ByID(1257240193);
}

/**
 * UpdatePersona updates name and prompt for an existing persona.
 */
export function UpdatePersona(id: number, name: string, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(1951612024, id, name, prompt);
}

// Private type creation functions
const $$createType0 = $models.Conversation.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Persona.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = $models.Message.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType2);
const $$createType10 = $Create.Map($Create.Any, $$createType8);
