// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateConversation():Promise<main.Conversation>;

export function DeleteConversation(arg1:number):Promise<void>;

export function GetConversations():Promise<Array<main.Conversation>>;

export function GetMessages(arg1:number):Promise<Array<main.Message>>;

export function GetSettings():Promise<Record<string, string>>;

export function RegenerateMessage(arg1:number):Promise<string>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchMessages(arg1:string):Promise<Record<number, Array<main.Message>>>;

export function SelectFile():Promise<string>;

export function SendMessage(arg1:number,arg2:string):Promise<string>;

export function SendMessageWithImages(arg1:number,arg2:string,arg3:Array<string>):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<string>;
