// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbortMessage():Promise<void>;

export function CreateConversation():Promise<main.Conversation>;

export function CreatePersona(arg1:string,arg2:string):Promise<main.Persona>;

export function DeleteAllConversations():Promise<void>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeletePersona(arg1:number):Promise<void>;

export function GetActivePersonaID():Promise<string>;

export function GetAvailableProviders():Promise<Array<Record<string, string>>>;

export function GetConversations():Promise<Array<main.Conversation>>;

export function GetDefaultSystemPrompt():Promise<string>;

export function GetMessages(arg1:number):Promise<Array<main.Message>>;

export function GetPersonas():Promise<Array<main.Persona>>;

export function GetSettings():Promise<Record<string, string>>;

export function IsAuthenticated():Promise<boolean>;

export function OpenPath(arg1:string):Promise<string>;

export function RegenerateMessage(arg1:number,arg2:number,arg3:string):Promise<string>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function SearchMessages(arg1:string):Promise<Record<number, Array<main.Message>>>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SendMessage(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SendMessageWithImages(arg1:number,arg2:string,arg3:Array<string>,arg4:string,arg5:string):Promise<string>;

export function SetActivePersonaID(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SignIn():Promise<string>;

export function SignOut():Promise<void>;

export function TestConnection():Promise<string>;

export function UpdatePersona(arg1:number,arg2:string,arg3:string):Promise<void>;
