// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMessage() {
  return window['go']['main']['App']['AbortMessage']();
}

export function CreateConversation() {
  return window['go']['main']['App']['CreateConversation']();
}

export function CreatePersona(arg1, arg2) {
  return window['go']['main']['App']['CreatePersona'](arg1, arg2);
}

export function DeleteAllConversations() {
  return window['go']['main']['App']['DeleteAllConversations']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeletePersona(arg1) {
  return window['go']['main']['App']['DeletePersona'](arg1);
}

export function GetActivePersonaID() {
  return window['go']['main']['App']['GetActivePersonaID']();
}

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetDefaultSystemPrompt() {
  return window['go']['main']['App']['GetDefaultSystemPrompt']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetPersonas() {
  return window['go']['main']['App']['GetPersonas']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function RegenerateMessage(arg1, arg2) {
  return window['go']['main']['App']['RegenerateMessage'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchMessages(arg1) {
  return window['go']['main']['App']['SearchMessages'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMessageWithImages(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMessageWithImages'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActivePersonaID(arg1) {
  return window['go']['main']['App']['SetActivePersonaID'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SignIn() {
  return window['go']['main']['App']['SignIn']();
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function UpdatePersona(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePersona'](arg1, arg2, arg3);
}
