// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['Updater']['CheckForUpdate']();
}

export function DownloadAndInstall(arg1, arg2) {
  return window['go']['main']['Updater']['DownloadAndInstall'](arg1, arg2);
}

export function GetCurrentVersion() {
  return window['go']['main']['Updater']['GetCurrentVersion']();
}

export function GetWindowsDefenderExclusion() {
  return window['go']['main']['Updater']['GetWindowsDefenderExclusion']();
}
